version: '2'
services:
  mongodb:
    image: "mongo"
    ports:
     - "27017:27017"
  backend:
    build: ./
    ports:
      - "5555:5555"
    volumes:
      - ./app
    depends_on:
      - mongodb
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client
    depends_on:
      - backend